"""Rough Draft level: build level data + graph-paper art from a hitbox PNG.
usage: python3 tools/build_level.py hitbox.png
Outputs: public/level_rough_draft.js (collision rects) and public/Assets/Images/Levels/RoughDraft.png (art)."""
import sys, json
import numpy as np
from PIL import Image
from scipy import ndimage as ndi

src = sys.argv[1] if len(sys.argv) > 1 else 'public/Assets/Images/Levels/Hitboxes/RoughDraft.png'
m = np.array(Image.open(src))[:, :, 3] > 128
H, W = m.shape

# collision rects (row runs merged vertically)
rects = []; prev = {}
for y in range(H):
    d = np.diff(np.concatenate([[0], m[y].astype(np.int8), [0]]))
    s = np.where(d == 1)[0]; e = np.where(d == -1)[0]
    cur = {}
    for a, b in zip(s, e):
        k = (int(a), int(b))
        cur[k] = prev.pop(k) if k in prev else y
    for k, y0 in prev.items(): rects.append([k[0], y0, k[1] - k[0], y - y0])
    prev = cur
for k, y0 in prev.items(): rects.append([k[0], y0, k[1] - k[0], H - y0])
open('public/level_rough_draft.js', 'w').write(
    '// generated by tools/build_level.py, do not edit by hand\n'
    f'const LEVEL_ROUGH_DRAFT = {{ w: {W}, h: {H}, rects: {json.dumps(rects, separators=(",", ":"))} }};\n')

# graph paper art
BLUE = np.array([0x96, 0xAD, 0xE9], float)
SP, LW, OUT = 28, 1.2, 4.0          # grid spacing, line half-width, outline width
yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
def band(v):
    mm = np.mod(v, SP); return np.minimum(mm, SP - mm) / np.sqrt(2)
d = np.minimum(band(xx + yy), band(xx - yy))
grid = np.clip(LW + 0.5 - d, 0, 1) * 0.55           # soft diagonal lines

pad = np.pad(m, 1, constant_values=False)
inside = ndi.distance_transform_edt(pad)[1:-1, 1:-1]  # distance to nearest empty pixel
outline = np.clip(OUT + 0.5 - inside, 0, 1)
cover = np.clip(inside, 0, 1)                          # shape coverage (0 outside)

paper = np.array([0xF4, 0xF8, 0xFF], float)
a_line = np.maximum(grid, outline)
rgb = paper[None, None, :] * (1 - a_line[..., None]) + BLUE[None, None, :] * a_line[..., None]
img = np.dstack([rgb, cover * 255]).astype(np.uint8)
Image.fromarray(img, 'RGBA').save('public/Assets/Images/Levels/RoughDraft.png')
print(W, H, len(rects), 'rects')
